// RETIREMENT/EXPAT COUNTRY COMPARISON DATA
// Sources: InterNations Expat Insider 2024, Numbeo 2025, International Living 2025
// Last Updated: February 2026

const countryData = [
    // TOP 10 from InterNations 2024
    {
        rank: 1,
        country: "Panama",
        region: "Central America",
        overall: 92,
        healthcare: 78,
        cost: 88,
        safety: 72,
        quality: 89,
        easeOfEntry: 95,
        expatCommunity: 85
    },
    {
        rank: 2,
        country: "Mexico",
        region: "North America",
        overall: 89,
        healthcare: 75,
        cost: 90,
        safety: 68,
        quality: 87,
        easeOfEntry: 92,
        expatCommunity: 90
    },
    {
        rank: 3,
        country: "Indonesia",
        region: "Southeast Asia",
        overall: 88,
        healthcare: 70,
        cost: 95,
        safety: 75,
        quality: 85,
        easeOfEntry: 85,
        expatCommunity: 80
    },
    {
        rank: 4,
        country: "Spain",
        region: "Southern Europe",
        overall: 87,
        healthcare: 92,
        cost: 75,
        safety: 85,
        quality: 95,
        easeOfEntry: 88,
        expatCommunity: 88
    },
    {
        rank: 5,
        country: "Colombia",
        region: "South America",
        overall: 86,
        healthcare: 72,
        cost: 92,
        safety: 65,
        quality: 82,
        easeOfEntry: 88,
        expatCommunity: 82
    },
    {
        rank: 6,
        country: "Thailand",
        region: "Southeast Asia",
        overall: 85,
        healthcare: 80,
        cost: 94,
        safety: 82,
        quality: 88,
        easeOfEntry: 90,
        expatCommunity: 85
    },
    {
        rank: 7,
        country: "Brazil",
        region: "South America",
        overall: 84,
        healthcare: 68,
        cost: 88,
        safety: 60,
        quality: 80,
        easeOfEntry: 85,
        expatCommunity: 78
    },
    {
        rank: 8,
        country: "Vietnam",
        region: "Southeast Asia",
        overall: 83,
        healthcare: 72,
        cost: 96,
        safety: 80,
        quality: 78,
        easeOfEntry: 82,
        expatCommunity: 75
    },
    {
        rank: 9,
        country: "United Arab Emirates",
        region: "Middle East",
        overall: 82,
        healthcare: 88,
        cost: 65,
        safety: 95,
        quality: 90,
        easeOfEntry: 85,
        expatCommunity: 92
    },
    {
        rank: 10,
        country: "Costa Rica",
        region: "Central America",
        overall: 81,
        healthcare: 82,
        cost: 78,
        safety: 78,
        quality: 88,
        easeOfEntry: 90,
        expatCommunity: 85
    },
    
    // 11-25: Strong contenders
    {
        rank: 11,
        country: "Portugal",
        region: "Southern Europe",
        overall: 80,
        healthcare: 88,
        cost: 72,
        safety: 90,
        quality: 92,
        easeOfEntry: 92,
        expatCommunity: 88
    },
    {
        rank: 12,
        country: "Malaysia",
        region: "Southeast Asia",
        overall: 79,
        healthcare: 85,
        cost: 91,
        safety: 80,
        quality: 82,
        easeOfEntry: 88,
        expatCommunity: 82
    },
    {
        rank: 13,
        country: "Ecuador",
        region: "South America",
        overall: 78,
        healthcare: 70,
        cost: 93,
        safety: 68,
        quality: 78,
        easeOfEntry: 88,
        expatCommunity: 80
    },
    {
        rank: 14,
        country: "Cyprus",
        region: "Mediterranean",
        overall: 77,
        healthcare: 82,
        cost: 70,
        safety: 88,
        quality: 85,
        easeOfEntry: 85,
        expatCommunity: 80
    },
    {
        rank: 15,
        country: "Philippines",
        region: "Southeast Asia",
        overall: 76,
        healthcare: 68,
        cost: 92,
        safety: 70,
        quality: 75,
        easeOfEntry: 90,
        expatCommunity: 78
    },
    {
        rank: 16,
        country: "Czechia",
        region: "Central Europe",
        overall: 75,
        healthcare: 85,
        cost: 78,
        safety: 85,
        quality: 82,
        easeOfEntry: 75,
        expatCommunity: 72
    },
    {
        rank: 17,
        country: "Greece",
        region: "Southern Europe",
        overall: 74,
        healthcare: 80,
        cost: 75,
        safety: 82,
        quality: 88,
        easeOfEntry: 80,
        expatCommunity: 75
    },
    {
        rank: 18,
        country: "Poland",
        region: "Central Europe",
        overall: 73,
        healthcare: 78,
        cost: 82,
        safety: 82,
        quality: 75,
        easeOfEntry: 75,
        expatCommunity: 68
    },
    {
        rank: 19,
        country: "Hungary",
        region: "Central Europe",
        overall: 72,
        healthcare: 75,
        cost: 85,
        safety: 78,
        quality: 72,
        easeOfEntry: 78,
        expatCommunity: 65
    },
    {
        rank: 20,
        country: "Argentina",
        region: "South America",
        overall: 71,
        healthcare: 75,
        cost: 86,
        safety: 62,
        quality: 75,
        easeOfEntry: 78,
        expatCommunity: 70
    },
    {
        rank: 21,
        country: "Uruguay",
        region: "South America",
        overall: 70,
        healthcare: 78,
        cost: 72,
        safety: 80,
        quality: 80,
        easeOfEntry: 75,
        expatCommunity: 68
    },
    {
        rank: 22,
        country: "Nicaragua",
        region: "Central America",
        overall: 69,
        healthcare: 62,
        cost: 95,
        safety: 65,
        quality: 68,
        easeOfEntry: 82,
        expatCommunity: 70
    },
    {
        rank: 23,
        country: "Italy",
        region: "Southern Europe",
        overall: 68,
        healthcare: 90,
        cost: 65,
        safety: 80,
        quality: 90,
        easeOfEntry: 70,
        expatCommunity: 75
    },
    {
        rank: 24,
        country: "Malta",
        region: "Mediterranean",
        overall: 67,
        healthcare: 82,
        cost: 68,
        safety: 85,
        quality: 78,
        easeOfEntry: 88,
        expatCommunity: 75
    },
    {
        rank: 25,
        country: "Croatia",
        region: "Southern Europe",
        overall: 66,
        healthcare: 75,
        cost: 75,
        safety: 85,
        quality: 82,
        easeOfEntry: 75,
        expatCommunity: 65
    },
    
    // 26-50: Good options
    {
        rank: 26,
        country: "Netherlands",
        region: "Western Europe",
        overall: 65,
        healthcare: 95,
        cost: 55,
        safety: 90,
        quality: 92,
        easeOfEntry: 75,
        expatCommunity: 70
    },
    {
        rank: 27,
        country: "Peru",
        region: "South America",
        overall: 64,
        healthcare: 68,
        cost: 88,
        safety: 60,
        quality: 70,
        easeOfEntry: 80,
        expatCommunity: 65
    },
    {
        rank: 28,
        country: "Chile",
        region: "South America",
        overall: 63,
        healthcare: 78,
        cost: 68,
        safety: 72,
        quality: 78,
        easeOfEntry: 72,
        expatCommunity: 62
    },
    {
        rank: 29,
        country: "South Africa",
        region: "Africa",
        overall: 62,
        healthcare: 70,
        cost: 85,
        safety: 48,
        quality: 72,
        easeOfEntry: 75,
        expatCommunity: 70
    },
    {
        rank: 30,
        country: "Morocco",
        region: "North Africa",
        overall: 61,
        healthcare: 65,
        cost: 90,
        safety: 72,
        quality: 68,
        easeOfEntry: 70,
        expatCommunity: 60
    },
    {
        rank: 31,
        country: "Tunisia",
        region: "North Africa",
        overall: 60,
        healthcare: 68,
        cost: 92,
        safety: 65,
        quality: 65,
        easeOfEntry: 68,
        expatCommunity: 55
    },
    {
        rank: 32,
        country: "India",
        region: "South Asia",
        overall: 59,
        healthcare: 62,
        cost: 94,
        safety: 58,
        quality: 55,
        easeOfEntry: 70,
        expatCommunity: 65
    },
    {
        rank: 33,
        country: "Albania",
        region: "Southern Europe",
        overall: 58,
        healthcare: 60,
        cost: 93,
        safety: 75,
        quality: 65,
        easeOfEntry: 78,
        expatCommunity: 52
    },
    {
        rank: 34,
        country: "Bulgaria",
        region: "Eastern Europe",
        overall: 57,
        healthcare: 65,
        cost: 88,
        safety: 75,
        quality: 68,
        easeOfEntry: 75,
        expatCommunity: 55
    },
    {
        rank: 35,
        country: "Romania",
        region: "Eastern Europe",
        overall: 56,
        healthcare: 68,
        cost: 86,
        safety: 72,
        quality: 70,
        easeOfEntry: 72,
        expatCommunity: 52
    },
    {
        rank: 36,
        country: "Cambodia",
        region: "Southeast Asia",
        overall: 55,
        healthcare: 58,
        cost: 94,
        safety: 68,
        quality: 62,
        easeOfEntry: 85,
        expatCommunity: 65
    },
    {
        rank: 37,
        country: "Belize",
        region: "Central America",
        overall: 54,
        healthcare: 60,
        cost: 75,
        safety: 65,
        quality: 72,
        easeOfEntry: 88,
        expatCommunity: 68
    },
    {
        rank: 38,
        country: "France",
        region: "Western Europe",
        overall: 53,
        healthcare: 95,
        cost: 52,
        safety: 78,
        quality: 88,
        easeOfEntry: 65,
        expatCommunity: 70
    },
    {
        rank: 39,
        country: "Turkey",
        region: "Middle East/Europe",
        overall: 52,
        healthcare: 75,
        cost: 80,
        safety: 62,
        quality: 68,
        easeOfEntry: 68,
        expatCommunity: 65
    },
    {
        rank: 40,
        country: "Dominican Republic",
        region: "Caribbean",
        overall: 51,
        healthcare: 65,
        cost: 82,
        safety: 60,
        quality: 70,
        easeOfEntry: 85,
        expatCommunity: 70
    },
    {
        rank: 41,
        country: "Montenegro",
        region: "Southern Europe",
        overall: 50,
        healthcare: 62,
        cost: 80,
        safety: 78,
        quality: 68,
        easeOfEntry: 75,
        expatCommunity: 50
    },
    {
        rank: 42,
        country: "Georgia",
        region: "Caucasus",
        overall: 49,
        healthcare: 65,
        cost: 90,
        safety: 75,
        quality: 65,
        easeOfEntry: 82,
        expatCommunity: 55
    },
    {
        rank: 43,
        country: "Sri Lanka",
        region: "South Asia",
        overall: 48,
        healthcare: 68,
        cost: 91,
        safety: 58,
        quality: 62,
        easeOfEntry: 75,
        expatCommunity: 52
    },
    {
        rank: 44,
        country: "Slovenia",
        region: "Central Europe",
        overall: 47,
        healthcare: 80,
        cost: 68,
        safety: 88,
        quality: 78,
        easeOfEntry: 70,
        expatCommunity: 48
    },
    {
        rank: 45,
        country: "Slovakia",
        region: "Central Europe",
        overall: 46,
        healthcare: 75,
        cost: 75,
        safety: 80,
        quality: 70,
        easeOfEntry: 70,
        expatCommunity: 45
    },
    {
        rank: 46,
        country: "Estonia",
        region: "Northern Europe",
        overall: 45,
        healthcare: 78,
        cost: 72,
        safety: 85,
        quality: 75,
        easeOfEntry: 75,
        expatCommunity: 48
    },
    {
        rank: 47,
        country: "Latvia",
        region: "Northern Europe",
        overall: 44,
        healthcare: 72,
        cost: 75,
        safety: 80,
        quality: 70,
        easeOfEntry: 72,
        expatCommunity: 45
    },
    {
        rank: 48,
        country: "Lithuania",
        region: "Northern Europe",
        overall: 43,
        healthcare: 75,
        cost: 78,
        safety: 82,
        quality: 72,
        easeOfEntry: 72,
        expatCommunity: 42
    },
    {
        rank: 49,
        country: "Laos",
        region: "Southeast Asia",
        overall: 42,
        healthcare: 55,
        cost: 93,
        safety: 70,
        quality: 58,
        easeOfEntry: 80,
        expatCommunity: 50
    },
    {
        rank: 50,
        country: "Guatemala",
        region: "Central America",
        overall: 41,
        healthcare: 58,
        cost: 89,
        safety: 55,
        quality: 62,
        easeOfEntry: 75,
        expatCommunity: 58
    }
];
